# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.2
matrix:
  fast_finish: true
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
    - stage: "Test"
      name: "GridapGmshTest"
      julia: 1.2
      os: linux
      branches:
        only:
          - new_master
      before_script:
        - curl -OL http://gmsh.info/bin/Linux/gmsh-4.4.1-Linux64-sdk.tgz
        - tar xfv gmsh-4.4.1-Linux64-sdk.tgz
        - GMSHROOT=`pwd`/gmsh-4.4.1-Linux64-sdk
        - export PATH=$PATH:$GMSHROOT/bin
        - mkdir -p tmp
      script:
        - julia --project=tmp/ -e 'using Pkg;
                                   Pkg.develop(PackageSpec(path=pwd()));
                                   Pkg.instantiate();
                                   Pkg.add(PackageSpec(name="GridapGmsh",rev="new_master"));
                                   Pkg.build("GridapGmsh");
                                   Pkg.test("GridapGmsh");'
      after_success: skip
